### ISSUE TITLE
How to correctly set `persistence`?

### ISSUE THREAD

**Issue by stefanobartoletti** [mitjans/nuxt-posthog#28]
Hi, thanks for this module!

I'm trying to correctly set the `persistence: 'memory'` to avoid using cookies, but I'm unable to do so apparently.

I tried to put this in my Nuxt config

```js
  posthog: {
    clientOptions: {
      persistence: 'memory',
    },
  },
```

As it seems, by reading the docs here https://nuxt-posthog.cmitjans.dev/configuration, that this is the correct way to pass config options.

Anyway, on my deployed site, cookies are still set, and I need to prevent this.

I checked and it seems that these options are not correctly passed, I have some error thrown inside vscode

![Screenshot_20240417_175347](https://github.com/mitjans/nuxt-posthog/assets/36746429/5751dafd-24ab-4ec0-9e97-c24eea6dffbb)

Just to try, I added another random property (`autocomplete` just to test) and the highlighted number went to 46.
Apparently it seems that the module is expecting me to pass all the possible properties down? Maybe there is some misconfiguration on my part, but I did everything by the docs, and it seems like there is some issue in merging the user settings with the default values .

Also, but I don't know if this can be an issue or not, by inspecting the module code, I noticed that the clientOptions is missing from the defaults, bu

![Screenshot_20240417_181121](https://github.com/mitjans/nuxt-posthog/assets/36746429/ca61c93f-d976-474c-ad35-81aa734fc18f)

Let me know if I can provide more info or context :)

**Comment by stefanobartoletti** [comment]
Ok I did some more research, and I don't know if all of this is relevant as I am not familiar with the module inner workings, but here is what I get on the site frontend once loaded:

![Screenshot_20240417_182457](https://github.com/mitjans/nuxt-posthog/assets/36746429/70d352bb-baa2-4e23-a738-9a19114da503)
 
 As you can see the `persistence` property is nested inside `clientOptions`, inside the `posthog` key. So the previous error is not preventing this property to be passed, but still I suspect that is not merged correctly in the right place.
 
 Before trying this module, I was resorting in the basic script inclusion, like this
 
 
![Screenshot_20240417_182955](https://github.com/mitjans/nuxt-posthog/assets/36746429/ca449be7-c54f-4901-b8ea-a3018820b516)

And this worked perfectly, the property was correctly read and no cookies were set. I moved out of this config because I needed PostHog to correctly detect different pages. 

I hope you didn't mind the long report, and again, let me know if you need more info, I am willing to help in any way I can :)

**Comment by mitjans** [comment]
Thanks for the detailed information @stefanobartoletti! I'll take a look later today or tomorrow 🙏

**Comment by stefanobartoletti** [comment]
No worries, I'm not in a hurry, at the moment I resorted to manually implementing according to this https://posthog.com/docs/libraries/nuxt-js

**Comment by mitjans** [comment]
So, I've fixed the problem with the typings in the config file (thanks for spotting that!).

However, I cannot reproduce the issue in the module's playground. When I set the configuration to `'memory'`, no PostHog cookies are created and a new Session Id is created when the page is refreshed.

I'll try again with a different project after a pre-release of the module and let you know. 👍

**Comment by mitjans** [comment]
Hey @stefanobartoletti! Can you try with the new pre-release version `1.5.0`?

**Comment by stefanobartoletti** [comment]
Sorry for the delay, I've been quite busy.

I tried to set up a new project within PostHog to test this, but it looks like in the free tier I'm not allowed to have more than one.

At the moment my main site, where I set up the script manually, is in quite important moment, and I need to keep the visits tracked steadily and without possible issues.

Do you have some suggestions about how I can find a way to test it nonetheless?

**Comment by mitjans** [comment]
Hey @stefanobartoletti sorry for the late answer.

Have you tried setting up a new PostHog account with a new email? Just for testing purposes. You should be able to test this without having to touch your production application.

Have you found if the problem persists after release 1.5.0?

**Comment by stefanobartoletti** [comment]
@mitjans sorry for the very late answer, I was able to setup a new project using your module.

This problem seems to be still present.

The project is hosted here: https://nuxt-social-share.stefanobartoletti.it/

And you can see my current configuration here, here I've set `persistence: 'memory'` :

https://github.com/stefanobartoletti/nuxt-social-share/blob/4d6bf5329bc18397ae994e7916c2400f13c03894/docs/nuxt.config.ts#L74C1-L78C4


Despite this, I still have a cookie set on my site:


![Screenshot_20241003_082830](https://github.com/user-attachments/assets/2989af28-c780-47c1-b9de-f5236923b7b5)

**Comment by mitjans** [comment]
Hi @stefanobartoletti! I am not able to reproduce this problem with your site. Is it possible that it was an old cookie not yet been deleted? Can you confirm you still have the issue?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/34f0194d-8576-442e-bd14-82a8a8497842">
